# Generated by Django 4.2.7 on 2023-11-20 19:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_course_name_alter_department_name'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('unit_name', models.CharField(max_length=200)),
                ('unit_code', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.course')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
