# Generated by Django 4.2.7 on 2023-11-20 19:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_is_student'),
        ('academics', '0003_alter_units_unit_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUnits',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.units')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
