# Generated by Django 4.2.7 on 2023-11-20 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_attendance_unit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
    ]
